### ISSUE TITLE
AttributeError for list of discriminated unions

### ISSUE THREAD

**Issue by lumpi101** [RenaudLN/dash-pydantic-form#51]
I tried to build the "Discriminated unions" example from the readme.md but with a list of such employees. I.e. I have a ``EmployeeList`` model which contains a ``employees: list[Employee]`` attribute.

Executing the code, I get a ``AttributeError: 'EmployeeList' object has no attribute 'employees'``.

The code and relevant exception traceback are as follows:
```python
from typing import Literal
from dash_pydantic_form import ModelForm
from pydantic import BaseModel, Field

class HomeOffice(BaseModel):
    """Home office model."""
    type: Literal["home_office"]
    has_workstation: bool = Field(title="Has workstation", description="Does the employee have a suitable workstation")

class WorkOffice(BaseModel):
    """Work office model."""
    type: Literal["work_office"]
    commute_time: int = Field(title="Commute time", description="Commute time in minutes", ge=0)

class Employee(BaseModel):
    name: str = Field(title="Name")
    work_location: HomeOffice | WorkOffice | None = Field(title="Work location", default=None, discriminator="type")

class EmployeeList(BaseModel):
    employees: list[Employee] = Field(title="Employees")

form = ModelForm(EmployeeList, aio_id="employees", form_id="new_employee")
```

```
  File "/some/folder/src/some/file.py", line 29, in <module>
    form = ModelForm(
           ^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/model_form.py", line 130, in __init__
    field_inputs = self.render_fields(
                   ^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/model_form.py", line 245, in render_fields
    field_inputs[field_name] = field_repr.render(
                               ^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/fields/base_fields.py", line 168, in render
    inputs = self._render(
             ^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/fields/list_field.py", line 495, in _render
    template = self.render_type_item_mapper(self.render_type)(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/fields/list_field.py", line 137, in accordion_item
    ModelForm(
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/model_form.py", line 130, in __init__
    field_inputs = self.render_fields(
                   ^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/model_form.py", line 245, in render_fields
    field_inputs[field_name] = field_repr.render(
                               ^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/fields/base_fields.py", line 168, in render
    inputs = self._render(
             ^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/fields/model_field.py", line 204, in _render
    input_ = self.accordion_item(item, aio_id, form_id, field, parent, field_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/fields/model_field.py", line 154, in accordion_item
    ModelForm(
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/model_form.py", line 128, in __init__
    subitem_cls, disc_vals = self.get_discriminated_subitem_cls(item=item, path=path, discriminator=discriminator)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/model_form.py", line 192, in get_discriminated_subitem_cls
    subitem = get_subitem(item, path)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/dash_pydantic_form/utils.py", line 171, in get_subitem
    next_item = getattr(item, first_part)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/some/venv/lib/python3.11/site-packages/pydantic/main.py", line 896, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'EmployeeList' object has no attribute 'employees'
```

**Comment by RenaudLN** [comment]
This has just been fixed in 0.9.2!

**Comment by lumpi101** [comment]
I just updated my version to 0.9.2 but the error remains. Also the error stack trace keeps being the same, just some line numbers changed.
I hope that's no misconfiguration on my side but I am quite sure I am running on 0.9.2, now.

**Comment by RenaudLN** [comment]
The issue comes from your EmployeeList model, you need to set a default value of either None or a default_factory=list

**Comment by lumpi101** [comment]
That solved my issue. Thanks!
