### ISSUE TITLE
Nested fields_repr

### ISSUE THREAD

**Issue by mvheimburg** [RenaudLN/dash-pydantic-form#85]
I am trying to force a selectable field within a table or list. I fails at nesting the model dump in ModelForm.render_fields. 

Changing this line:
`field_repr = field_repr.__class__(**(field_repr.model_dump() | more_kwargs))`

to:
`field_repr = field_repr.__class__(**(dict(field_repr)| more_kwargs))`

Makes it work somehow. Although seems like a quirk that the first line i the table forgets its value...

My code for the form. 
```
def resourceform(mods: Modalities, resource: ResourceModel | type[ResourceModel] = ResourceModel):
    select = [{"label":n,"value":n} for n in mods.names]
    return ModelForm(
    resource,
    aio_id="resources",
    form_id="new_resource",
    fields_repr={
        "modalities": fields.Table(
            fields_repr={
                "modality": fields.Select(
                    data = select
                )
            },
        )
    },
    excluded_fields=['id']
)
```

**Comment by RenaudLN** [comment]
I need to look into it (I'm away at the moment) but you can try this as a quick fix (no need to specify Select):

```py
fields.Table(
    fields_repr={
        "modality": {"data": select},
    },
)
```

**Comment by mvheimburg** [comment]
Hi, yeah that does not work. Probably important to note that "modality" is not an Enum or Literal as the select values are dynamically available runtime only. So if not specified as Select it's just interpreted as a text input.

**Comment by mvheimburg** [comment]
Any chance at looking at this? I believe my initial fix is doing the job quite nicely. The quirk I saw was due to other issues, but might be other drawbacks I'm not seeing?

**Comment by RenaudLN** [comment]
This should now be fixed in 0.14.9 :)

**Comment by mvheimburg** [comment]
Hi, 

did you test on attributes not in [Enum, Literal]? 

This still does not work for my part unfortunately...

**Comment by RenaudLN** [comment]
I meant that the `fields_repr` nesting should now work properly, is that not the case?

**Comment by mvheimburg** [comment]
Hi, yeah I'm still only able to force field to e.g Select on the top level. Here is an example app illustrating the problem:

```

from dash import Dash, html, Input, Output, State
from dash.exceptions import PreventUpdate
from dash import _dash_renderer
_dash_renderer._set_react_version("18.2.0")

from dash_pydantic_form import ModelForm, fields
from dash_mantine_components import Button, Modal, Text, Container, MantineProvider
from pydantic import BaseModel


# Pydantic model for the form
class CountryList(BaseModel):
    country: str

# Pydantic model for the form
class CountryForm(BaseModel):
    list: CountryList

# Initialize the Dash app
app = Dash(__name__)

# Function to return modal in open state
def get_country_form(countries: list[str]):
    return ModelForm(
            CountryForm,
            aio_id="country-form",
            form_id="auto",
            fields_repr={
                "list": fields.Model(
                    fields_repr={
                        "country": fields.Select(data = [{"value": x, "label": x} for x in countries])
                    }
                )
            })
    

# Layout
app.layout = MantineProvider(
        children=Container([
        Text("Hello, World!", size="xl"),
        Button("Select Country", id="open-modal", n_clicks=0, mt=20),
        Modal(
            title="Choose a Country",
            id="modal",
            opened=False,
        
            children=[
                html.Div(id="modal-container"),
                
                Button("Submit", id="submit-form", n_clicks=0, mt=10),
                Button("Close", id="close-modal", n_clicks=0, mt=10, variant="light", color="red")
            ]
        ),    
        html.Div(id="output", style={"marginTop": "20px"})
    ])
)
# Callback to open the modal and insert it into the container
@app.callback(
    Output("modal", "opened"),
    Output("modal-container", "children"),
    Input("open-modal", "n_clicks"),
    prevent_initial_call=True
)
def display_modal(n_clicks):
    if n_clicks:
        countries = ['USA', 'Canada', 'Germany', 'Japan', 'Australia']
        form = get_country_form(countries)
        return True, form
    raise PreventUpdate

# Callback to handle form submission
@app.callback(
    Output("output", "children"),
    Input("submit-form", "n_clicks"),
    State(ModelForm.ids.main("country-form", "auto"), "data"),
    prevent_initial_call=True
)
def display_output(n_clicks, form_data):
    if n_clicks and form_data:
        return f"You selected: {form_data['country']}"
    return ""

# Run the app
if __name__ == "__main__":
    app.run(debug=True)

```

Here I would expect country to appear as a "Select" but it's still a str input. Changing line 361 in model_form.py as stated in my initial post seems to solve the problem.

**Comment by RenaudLN** [comment]
OK, found the edge case (it was working for tables). Fix incoming.

**Comment by mvheimburg** [comment]
Can I ask a for me related question on? If we go by the same case, and just extend it to include a continent selector:

```
from typing import Literal
from dash import Dash, html, Input, Output, State
from dash.exceptions import PreventUpdate
from dash import _dash_renderer
_dash_renderer._set_react_version("18.2.0")

from dash_pydantic_form import ModelForm, fields
from dash_mantine_components import Button, Modal, Text, Container, MantineProvider
from pydantic import BaseModel

EUROPE_COUNTRIES = ['Sweden', 'Netherlands', 'Germany', 'UK']
ASIA_COUNTRIES = ['China', 'India', 'Japan', 'Pakistan']

country_map={
    "Europe": EUROPE_COUNTRIES,
    "Asia": ASIA_COUNTRIES
}


# Pydantic model for the form
class CountryList(BaseModel):
    country: str

# Pydantic model for the form
class CountryForm(BaseModel):
    continent: Literal["Europe", "Asia"] = "Europe"
    list: CountryList

# Initialize the Dash app
app = Dash(__name__)

# Function to return modal in open state
def get_country_form(continent: str):
    countries = country_map[continent]
    return ModelForm(
            CountryForm,
            aio_id="country-form",
            form_id="auto",
            fields_repr={
                "continent": fields.Select(
                            value=continent),
                "list": fields.Model(
                    fields_repr={
                        "country": fields.Select(
                            value=countries[0],
                            data = [{"value": x, "label": x} for x in countries])
                    }
                )
            })
    

# Layout
app.layout = MantineProvider(
        children=Container([
        Text("Hello, World!", size="xl"),
        Button("Select Country", id="open-modal", n_clicks=0, mt=20),
        Modal(
            title="Choose a Country",
            id="modal",
            opened=False,
        
            children=[
                html.Div(id="modal-container"),
                
                Button("Submit", id="submit-form", n_clicks=0, mt=10),
                Button("Close", id="close-modal", n_clicks=0, mt=10, variant="light", color="red")
            ]
        ),    
        html.Div(id="output", style={"marginTop": "20px"})
    ])
)
# Callback to open the modal and insert it into the container
@app.callback(
    Output("modal", "opened"),
    Output("modal-container", "children"),
    Input("open-modal", "n_clicks"),
    prevent_initial_call=True
)
def display_modal(n_clicks):
    if n_clicks:
        form = get_country_form("Europe")
        return True, form
    raise PreventUpdate

# Callback to handle form submission
@app.callback(
    Output("output", "children"),
    Input("submit-form", "n_clicks"),
    State(ModelForm.ids.main("country-form", "auto"), "data"),
    prevent_initial_call=True
)
def display_output(n_clicks, form_data):
    if n_clicks and form_data:
        return f"You selected: {form_data['country']}"
    return ""

# Run the app
if __name__ == "__main__":
    app.run(debug=True)
```

How would you implement a solution to update the  "country" field data values based on the continent selection? I'm assuming I am just unable to locate the correct field ids to update here?

In advance, thanks for any help. Much appreciated :)

**Comment by RenaudLN** [comment]
Fix will be available in 0.15.1 soon-ish

**Comment by mvheimburg** [comment]
It works. Brilliant 👍 Thx for the incredibly fast response time!

**Comment by MartinSA04** [comment]
@RenaudLN 
Generally speaking the following line could be problematic:
`
field_repr = field_repr.__class__(**(field_repr.model_dump() | more_kwargs))
`
This is because pydantic v2 serializes subclasses using the annotated class as default. See https://docs.pydantic.dev/latest/concepts/serialization/#serializeasany-annotation

The form_layout field in ListField is annotated as FormLayout, but if the actual value is for example AccordionFormLayout, the sections attribute is lost in serialisation.

changing the line to 
`
field_repr = field_repr.__class__(**(field_repr.model_dump(serialize_as_any=True) | more_kwargs))
`
is a safer option as this serializes the fields as their actual type, not their annotated type, which is probably the root cause of this issue.

**Comment by MartinSA04** [comment]
The best way is however probably to change type annotating from 
`form_layout: FormLayout`
to
`form_layout: SerializeAsAny[FormLayout]`
as then you have complete control.
